name: Delete a file

on:
  workflow_dispatch:

jobs:
  delete-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Delete file
        run: |
          rm -rf ./ip2.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        #with:
          #commit_message: "Create text file via GitHub Actions"
          #branch: ${{ github.ref }}
          #commit_user_name: "ip_get Action"
          #commit_user_email: "action@github.com"