name: Delete a file

on:
  workflow_dispatch:

jobs:
  delete-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Delete file
        run: |
          rm -rf ./test.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}